package vistas;

import controlador.ControladorCliente;
import controlador.ControladorProducto;
import controlador.ControladorReportes;
import controlador.ControladorVendedor;
import controlador.ControladorVenta;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 * @author Kevin Oliva
 */
public class PrincipalFormulario extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFormulario
     */
    public PrincipalFormulario() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVendedorLogin = new javax.swing.JTextField();
        txtIdVendedorLogin = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        mnuMenu = new javax.swing.JMenu();
        mnuAyuda = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mnuGenerarVenta = new javax.swing.JMenuItem();
        mnuMantenimiento = new javax.swing.JMenu();
        mnuCliente = new javax.swing.JMenuItem();
        mnuProducto = new javax.swing.JMenuItem();
        mnuVendedor = new javax.swing.JMenuItem();
        mnuReporte = new javax.swing.JMenu();
        mnuReporteVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Id Vendedor:");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(10, 10, 110, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Vendedor:");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(10, 40, 100, 30);

        txtVendedorLogin.setEditable(false);
        desktopPane.add(txtVendedorLogin);
        txtVendedorLogin.setBounds(120, 50, 73, 24);

        txtIdVendedorLogin.setEditable(false);
        desktopPane.add(txtIdVendedorLogin);
        txtIdVendedorLogin.setBounds(120, 10, 73, 24);

        mnuMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        mnuMenu.setMnemonic('f');
        mnuMenu.setText("Menú");

        mnuAyuda.setMnemonic('o');
        mnuAyuda.setText("Ayuda");
        mnuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuAyuda);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setMnemonic('x');
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuSalir);

        menuBar.add(mnuMenu);

        mnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoventas.png"))); // NOI18N
        mnuVentas.setMnemonic('e');
        mnuVentas.setText("Ventas");

        mnuGenerarVenta.setMnemonic('t');
        mnuGenerarVenta.setText("Generar Venta");
        mnuGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGenerarVentaActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuGenerarVenta);

        menuBar.add(mnuVentas);

        mnuMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logomantenimiento.png"))); // NOI18N
        mnuMantenimiento.setMnemonic('h');
        mnuMantenimiento.setText("Mantenimiento");

        mnuCliente.setMnemonic('c');
        mnuCliente.setText("Cliente");
        mnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClienteActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuCliente);

        mnuProducto.setMnemonic('a');
        mnuProducto.setText("Producto");
        mnuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductoActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuProducto);

        mnuVendedor.setText("Vendedor");
        mnuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVendedorActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuVendedor);

        menuBar.add(mnuMantenimiento);

        mnuReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        mnuReporte.setText("Reporte");

        mnuReporteVentas.setText("Reporte de Ventas");
        mnuReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporteVentasActionPerformed(evt);
            }
        });
        mnuReporte.add(mnuReporteVentas);

        menuBar.add(mnuReporte);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVendedorActionPerformed
        Vendedor vendedorF = new Vendedor();
        ControladorVendedor controladorVendedor = new ControladorVendedor(vendedorF);
        centrarVentana(vendedorF);

    }//GEN-LAST:event_mnuVendedorActionPerformed

    private void mnuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductoActionPerformed
        Producto productoF = new Producto();
        ControladorProducto controladorProduc = new ControladorProducto(productoF);
        centrarVentana(productoF);
    }//GEN-LAST:event_mnuProductoActionPerformed

    private void mnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClienteActionPerformed
        Cliente clienteF = new Cliente();
        ControladorCliente controladorCli = new ControladorCliente(clienteF);
        centrarVentana(clienteF);
    }//GEN-LAST:event_mnuClienteActionPerformed

    private void mnuGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGenerarVentaActionPerformed
        Venta ventaF = new Venta();
        ControladorVenta controladorVenta = new ControladorVenta(ventaF);
        centrarVentana(ventaF);
    }//GEN-LAST:event_mnuGenerarVentaActionPerformed

    private void mnuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaActionPerformed
        Ayuda ayuda = new Ayuda();
        
        centrarVentana(ayuda);
    }//GEN-LAST:event_mnuAyudaActionPerformed

    private void mnuReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteVentasActionPerformed
        ReporteFactura reporteFactura = new ReporteFactura();
        ControladorReportes controladorReporte = new ControladorReportes(reporteFactura);
        centrarVentana(reporteFactura);
    }//GEN-LAST:event_mnuReporteVentasActionPerformed

    public void centrarVentana(JInternalFrame frame) {
        desktopPane.add(frame);
        Dimension dimPrincipalF = desktopPane.getSize();
        Dimension dimVentaF = frame.getSize();
        frame.setLocation((dimPrincipalF.width - dimVentaF.width) / 2, (dimPrincipalF.height - dimVentaF.height) / 2);
        frame.show();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAyuda;
    private javax.swing.JMenuItem mnuCliente;
    private javax.swing.JMenuItem mnuGenerarVenta;
    private javax.swing.JMenu mnuMantenimiento;
    private javax.swing.JMenu mnuMenu;
    private javax.swing.JMenuItem mnuProducto;
    private javax.swing.JMenu mnuReporte;
    private javax.swing.JMenuItem mnuReporteVentas;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuVendedor;
    private javax.swing.JMenu mnuVentas;
    public static javax.swing.JTextField txtIdVendedorLogin;
    public static javax.swing.JTextField txtVendedorLogin;
    // End of variables declaration//GEN-END:variables

}
